apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  sources:
    - repoURL: https://charts.jenkins.io
      chart: jenkins
      targetRevision: 5.9.28
      helm:
        valueFiles:
          - $values/gitops/values/jenkins.yaml
    - repoURL: https://github.com/myhome-automation/git-vsphere.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
