apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: 1.12.0
      helm:
        valueFiles:
          - $values/gitops/values/longhorn.yaml
    - repoURL: https://github.com/myhome-automation/git-vsphere.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
